In [1]:
import requests
import json
import pandas as pd
import time

In [13]:
fileName    = "allwine.csv";
region_df = pd.read_csv(fileName)
region_df

,name,country,region,state,varietal,price,description,merchant,address
0,Angels Landing Cabernet Sauvignon,United States,Napa Valley,California,Cabernet Sauvignon,22.99,"This Cabernet has it all. Ripe dark fruit, str...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
1,Angels Landing Merlot Napa,United States,Napa Valley,California,Merlot,16.99,"A rich mix of black fruit, hints of dark choco...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
2,Antale Veneto Rosso,Italy,Veneto,Veneto,Corvina,11.99,Producing every style of wine and with great s...,Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
3,Articulate Cabernet Sauvignon Walla Walla,United States,Walla Walla Valley,Washington,Cabernet Sauvignon,14.99,NaN,Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
4,Baus Family Cabernet Sauvignon Private Reserve,United States,Alexander Valley,California,Cabernet Sauvignon,16.99,"A full-bodied and rich Cabernet, this wine is ...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
...,...,...,...,...,...,...,...,...,...
4531,Souverain Merlot,United States,NaN,California,Merlot,9.99,Authentic - Wines that are the best expression...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4532,Buena Vista Chateau Buena Vista Cabernet Sauv...,United States,Napa County,California,Cabernet Sauvignon,34.99,In the 1860âs Buena Vista covered more than ...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4533,Robert Mondavi Private Selection Pinot Noir,United States,Central Coast,California,Pinot Noir,8.99,"Unlike other reds, Pinot Noir grapes prefer th...",Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4534,Lindemans Pinot Noir Bin 99,Australia,NaN,South Eastern Australia,Pinot Noir,5.99,Lindemanâs wines contain the spirit and pass...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4535,14 Hands Cabernet Sauvignon,United States,Columbia Valley,Washington,Cabernet Sauvignon,10.99,The inspiration for 14 Hands wines recalls a t...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"

In [24]:
pd.set_option('display.max_rows', 100)

In [42]:
test1 = region_df.groupby(['country','region', 'state']).size().reset_index().rename(columns={0:'count'})
test2 = test1.reset_index()
test3 = test2.rename(columns={"index": 'Region_Id'})

test3=test3.drop(['count'] , axis='columns')

     Region_Id        country              region              state
0            0      Argentina             Mendoza               Cuyo
1            1      Argentina             Mendoza            Mendoza
2            2      Argentina           Patagonia    Southern Region
3            3      Argentina               Salta  Andean North West
4            4      Australia      Adelaide Hills    South Australia
..         ...            ...                 ...                ...
413        413  United States  Walla Walla Valley         Washington
414        414  United States        Warren Hills         New Jersey
415        415  United States          Willamette             Oregon
416        416  United States   Willamette Valley             Oregon
417        417  United States         Yolo County         California

[418 rows x 4 columns]

In [54]:
test3.to_csv('region.csv', encoding='utf-8', index=False)

In [44]:
new_df = pd.merge(region_df, test3,  how='left', left_on=['country','region','state'], right_on = ['country','region','state'])
new_df = new_df.drop(['country','region', 'state', 'address' ] , axis='columns')

,name,varietal,price,description,merchant,Region_Id
0,Angels Landing Cabernet Sauvignon,Cabernet Sauvignon,22.99,"This Cabernet has it all. Ripe dark fruit, str...",Gary's Wayne,382.0
1,Angels Landing Merlot Napa,Merlot,16.99,"A rich mix of black fruit, hints of dark choco...",Gary's Wayne,382.0
2,Antale Veneto Rosso,Corvina,11.99,Producing every style of wine and with great s...,Gary's Wayne,296.0
3,Articulate Cabernet Sauvignon Walla Walla,Cabernet Sauvignon,14.99,NaN,Gary's Wayne,413.0
4,Baus Family Cabernet Sauvignon Private Reserve,Cabernet Sauvignon,16.99,"A full-bodied and rich Cabernet, this wine is ...",Gary's Wayne,352.0
...,...,...,...,...,...,...
4531,Souverain Merlot,Merlot,9.99,Authentic - Wines that are the best expression...,Petrocks Liquors,NaN
4532,Buena Vista Chateau Buena Vista Cabernet Sauv...,Cabernet Sauvignon,34.99,In the 1860âs Buena Vista covered more than ...,Petrocks Liquors,381.0
4533,Robert Mondavi Private Selection Pinot Noir,Pinot Noir,8.99,"Unlike other reds, Pinot Noir grapes prefer th...",Petrocks Liquors,358.0
4534,Lindemans Pinot Noir Bin 99,Pinot Noir,5.99,Lindemanâs wines contain the spirit and pass...,Petrocks Liquors,NaN
4535,14 Hands Cabernet Sauvignon,Cabernet Sauvignon,10.99,The inspiration for 14 Hands wines recalls a t...,Petrocks Liquors,362.0

In [55]:
new_df.to_csv('wine.csv', encoding='utf-8', index=False)

In [38]:
new_df.sort_values(by='Region_Id')

,name,country,region,state,varietal,price,description,merchant,address,Region_Id,count
2894,Tapiz Alta Collection Malbec 2017,Argentina,Mendoza,Cuyo,Uco Valley,19.99,The Sommelier Journal said Tapiz is a slam dun...,Chatham BottleKing,"41 Watchung Ave, Chatham, NJ, 07928",0.0,30.0
3477,Alta Vista Classic Malbec,Argentina,Mendoza,Cuyo,Malbec,12.99,"Established in 1998, Alta Vista is a French fa...",Chatham BottleKing,"41 Watchung Ave, Chatham, NJ, 07928",0.0,30.0
2564,Layer Cake Malbec,Argentina,Mendoza,Cuyo,Malbec,18.99,The once 5 mile wide Mendoza River is now most...,Chatham BottleKing,"41 Watchung Ave, Chatham, NJ, 07928",0.0,30.0
4140,Don Miguel Gascon Malbec,Argentina,Mendoza,Cuyo,Malbec,15.99,Tradition and innovation blended harmoniously ...,Chatham BottleKing,"41 Watchung Ave, Chatham, NJ, 07928",0.0,30.0
2517,Alamos Malbec,Argentina,Mendoza,Cuyo,Malbec,12.99,"From the vineyard to the winery, the Alamos wi...",Chatham BottleKing,"41 Watchung Ave, Chatham, NJ, 07928",0.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...
4528,Walter Hansel Estate Chardonnay Russian River...,United States,NaN,NaN,NaN,29.99,NaN,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844",NaN,NaN
4529,Dark Horse Pinot Noir,United States,NaN,California,Pinot Noir,7.99,"At Darkhorse wines, we challenge the belief th...",Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844",NaN,NaN
4530,Louis Latour Bourgogne Pinot Noir,France,NaN,Burgundy,Pinot Noir,19.99,"Over time, Maison Louis Latour has set an idea...",Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844",NaN,NaN
4531,Souverain Merlot,United States,NaN,California,Merlot,9.99,Authentic - Wines that are the best expression...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844",NaN,NaN
4534,Lindemans Pinot Noir Bin 99,Australia,NaN,South Eastern Australia,Pinot Noir,5.99,Lindemanâs wines contain the spirit and pass...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844",NaN,NaN

In [45]:
region_df

,name,country,region,state,varietal,price,description,merchant,address
0,Angels Landing Cabernet Sauvignon,United States,Napa Valley,California,Cabernet Sauvignon,22.99,"This Cabernet has it all. Ripe dark fruit, str...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
1,Angels Landing Merlot Napa,United States,Napa Valley,California,Merlot,16.99,"A rich mix of black fruit, hints of dark choco...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
2,Antale Veneto Rosso,Italy,Veneto,Veneto,Corvina,11.99,Producing every style of wine and with great s...,Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
3,Articulate Cabernet Sauvignon Walla Walla,United States,Walla Walla Valley,Washington,Cabernet Sauvignon,14.99,NaN,Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
4,Baus Family Cabernet Sauvignon Private Reserve,United States,Alexander Valley,California,Cabernet Sauvignon,16.99,"A full-bodied and rich Cabernet, this wine is ...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
...,...,...,...,...,...,...,...,...,...
4531,Souverain Merlot,United States,NaN,California,Merlot,9.99,Authentic - Wines that are the best expression...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4532,Buena Vista Chateau Buena Vista Cabernet Sauv...,United States,Napa County,California,Cabernet Sauvignon,34.99,In the 1860âs Buena Vista covered more than ...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4533,Robert Mondavi Private Selection Pinot Noir,United States,Central Coast,California,Pinot Noir,8.99,"Unlike other reds, Pinot Noir grapes prefer th...",Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4534,Lindemans Pinot Noir Bin 99,Australia,NaN,South Eastern Australia,Pinot Noir,5.99,Lindemanâs wines contain the spirit and pass...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
4535,14 Hands Cabernet Sauvignon,United States,Columbia Valley,Washington,Cabernet Sauvignon,10.99,The inspiration for 14 Hands wines recalls a t...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"

In [53]:
merchant_address = region_df.groupby(['merchant','address']).nunique()
merchant_address = merchant_address.drop(['name','country', 'state', 'region', 'varietal','price', 'description','merchant', 'address' ] , axis='columns')
merchant_address

Empty DataFrame
Columns: []
Index: [(Chatham BottleKing, 41 Watchung Ave, Chatham, NJ, 07928), (Gary's Wayne, 1308 NJ-23, Wayne, NJ 07470, USA), (Petrocks Liquors, 419 Amwell Road Hillsborough, NJ 08844)]

In [57]:
new_df.to_csv('merchant.csv', encoding='utf-8', index=False)