In [1]:
import requests
import json
import pandas as pd
import time
import numpy as np

In [2]:
#pd.set_option('max_rows', None)
fileName    = "allwine.csv"
region_df = pd.read_csv(fileName)
region_df=region_df.replace(np.nan,"na")
region_df

,name,country,region,state,varietal,price,description,merchant,address
0,Angels Landing Cabernet Sauvignon,United States,Napa Valley,California,Cabernet Sauvignon,22.99,"This Cabernet has it all. Ripe dark fruit, str...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
1,Angels Landing Merlot Napa,United States,Napa Valley,California,Merlot,16.99,"A rich mix of black fruit, hints of dark choco...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
2,Antale Veneto Rosso,Italy,Veneto,Veneto,Corvina,11.99,Producing every style of wine and with great s...,Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
3,Articulate Cabernet Sauvignon Walla Walla,United States,Walla Walla Valley,Washington,Cabernet Sauvignon,14.99,na,Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
4,Baus Family Cabernet Sauvignon Private Reserve,United States,Alexander Valley,California,Cabernet Sauvignon,16.99,"A full-bodied and rich Cabernet, this wine is ...",Gary's Wayne,"1308 NJ-23, Wayne, NJ 07470, USA"
...,...,...,...,...,...,...,...,...,...
6088,Candoni Pinot Grigio Organic,Italy,Pavia,Lombardy,Pinot Gris,11.99,Our Organic Pinot Grigio is made from 100% Org...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
6089,Canei Peach,Italy,na,na,na,7.99,Hand it over to an Italian to make an exciting...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
6090,Kendall Jackson Cabernet Grand Reserve,United States,North Coast,California,Cabernet Sauvignon,21.99,Grand Reserve is a winemakerâs blend of our ...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
6091,Bacchus Cabernet Sauvignon,United States,na,California,Cabernet Sauvignon,9.99,David Gordon has been the wine director at Tri...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"
6092,M Chapoutier Chateauneuf-Du-Pape La Bernardine,France,Southern Rhone,Rhone,Red Rhone Blend,49.99,ChÃ¢teauneuf-du-Pape is known for it amazing s...,Petrocks Liquors,"419 Amwell Road Hillsborough, NJ 08844"

In [3]:
test1 = region_df.groupby(['country','region', 'state']).size().reset_index().rename(columns={0:'count'})
test2 = test1.reset_index()
test3 = test2.rename(columns={"index": 'Region_Id'})
test3=test3.drop(['count'] , axis='columns')
test3

     Region_Id        country    region       state
0            0              ,        na          na
1            1      Argentina  Cafayate          na
2            2      Argentina       Est          na
3            3      Argentina   Mendoza        Cuyo
4            4      Argentina   Mendoza     Mendoza
..         ...            ...       ...         ...
791        791  United States        na  Washington
792        792  United States        na          na
793        793        Uruguay        na          na
794        794             na  Carneros  California
795        795             na        na          na

[796 rows x 4 columns]

In [4]:
test3.to_csv('region.csv', encoding='utf-8', index=False)

In [5]:
new_df = pd.merge(region_df, test3,  how='left', left_on=['country','region','state'], right_on = ['country','region','state'])
new_df = new_df.drop(['country','region', 'state', 'address' ] , axis='columns')
new_df

,name,varietal,price,description,merchant,Region_Id
0,Angels Landing Cabernet Sauvignon,Cabernet Sauvignon,22.99,"This Cabernet has it all. Ripe dark fruit, str...",Gary's Wayne,745
1,Angels Landing Merlot Napa,Merlot,16.99,"A rich mix of black fruit, hints of dark choco...",Gary's Wayne,745
2,Antale Veneto Rosso,Corvina,11.99,Producing every style of wine and with great s...,Gary's Wayne,482
3,Articulate Cabernet Sauvignon Walla Walla,Cabernet Sauvignon,14.99,na,Gary's Wayne,778
4,Baus Family Cabernet Sauvignon Private Reserve,Cabernet Sauvignon,16.99,"A full-bodied and rich Cabernet, this wine is ...",Gary's Wayne,712
...,...,...,...,...,...,...
6088,Candoni Pinot Grigio Organic,Pinot Gris,11.99,Our Organic Pinot Grigio is made from 100% Org...,Petrocks Liquors,433
6089,Canei Peach,na,7.99,Hand it over to an Italian to make an exciting...,Petrocks Liquors,523
6090,Kendall Jackson Cabernet Grand Reserve,Cabernet Sauvignon,21.99,Grand Reserve is a winemakerâs blend of our ...,Petrocks Liquors,755
6091,Bacchus Cabernet Sauvignon,Cabernet Sauvignon,9.99,David Gordon has been the wine director at Tri...,Petrocks Liquors,783
6092,M Chapoutier Chateauneuf-Du-Pape La Bernardine,Red Rhone Blend,49.99,ChÃ¢teauneuf-du-Pape is known for it amazing s...,Petrocks Liquors,263

In [6]:
new_df.to_csv('wine.csv', encoding='utf-8', index=False)

In [7]:
new_df.sort_values(by='Region_Id')

,name,varietal,price,description,merchant,Region_Id
6081,Tenuta Fiorebelli Coste Bianche Amarone,",",49.99,"""Exellent fruit, medium body, well balanced, w...",Petrocks Liquors,0
439,Don David Cabernet Sauvignon Reserve Michel To...,Cabernet Sauvignon,13.99,na,Gary's Wayne,1
2178,Michel Torino Cuma Torrontes Organic,Torrontes,9.95,na,Gary's Wayne,1
440,Don David Malbec Reserve,Malbec,13.99,"Vivacious red in color, this wine offers aroma...",Gary's Wayne,1
1511,Don David Tannat,Tannat,13.99,na,Gary's Wayne,1
...,...,...,...,...,...,...
1588,Family Winegrower 3 Pack,na,95,na,Gary's Wayne,795
738,2020 Salute A Tuti 3 Pack,na,29.99,na,Gary's Wayne,795
1597,2020 Father & Son Duo Phelps 2 Pack,na,195,na,Gary's Wayne,795
1566,Evolution Lucky No. 9 Boxed White Wine,na,17.99,na,Gary's Wayne,795
729,2020 Cheers 2 Pack,na,39.99,na,Gary's Wayne,795

In [8]:
merchant_address = region_df.groupby(['merchant','address']).nunique()
merchant_address = merchant_address.drop(['name','country', 'state', 'region', 'varietal','price', 'description','merchant', 'address' ] , axis='columns')
merch_add_df=merchant_address.reset_index()
merch_add_df

             merchant                                 address
0  Chatham BottleKing     41 Watchung Ave, Chatham, NJ, 07928
1        Gary's Wayne        1308 NJ-23, Wayne, NJ 07470, USA
2    Petrocks Liquors  419 Amwell Road Hillsborough, NJ 08844

In [9]:
merch_add_df.to_csv('merchant.csv', encoding='utf-8', index=False)

In [10]:
merchant_wine_df=new_df[['merchant','name']]
merchant_wine_df.reset_index(drop=True, inplace=True)
merchant_wine_df

              merchant                                             name
0         Gary's Wayne                Angels Landing Cabernet Sauvignon
1         Gary's Wayne                       Angels Landing Merlot Napa
2         Gary's Wayne                              Antale Veneto Rosso
3         Gary's Wayne        Articulate Cabernet Sauvignon Walla Walla
4         Gary's Wayne   Baus Family Cabernet Sauvignon Private Reserve
...                ...                                              ...
6088  Petrocks Liquors                     Candoni Pinot Grigio Organic
6089  Petrocks Liquors                                      Canei Peach
6090  Petrocks Liquors           Kendall Jackson Cabernet Grand Reserve
6091  Petrocks Liquors                       Bacchus Cabernet Sauvignon
6092  Petrocks Liquors   M Chapoutier Chateauneuf-Du-Pape La Bernardine

[6093 rows x 2 columns]

In [11]:
merchant_wine_df.to_csv("merchant_wine.csv",encoding='utf-8', index=False)